In [6]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [7]:
# Load datasets

providers = pd.read_csv("Data/providers_data.csv")
receivers = pd.read_csv("Data/receivers_data.csv")
food_listings = pd.read_csv("Data/food_listings_data.csv")
claims = pd.read_csv("Data/claims_data.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [8]:
print("Providers:", providers.shape)
print("Receivers:", receivers.shape)
print("Food Listings:", food_listings.shape)
print("Claims:", claims.shape)

Providers: (1000, 6)
Receivers: (1000, 5)
Food Listings: (1000, 9)
Claims: (1000, 5)

In [9]:
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577

In [10]:
providers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   Address      1000 non-null   str
 4   City         1000 non-null   str
 5   Contact      1000 non-null   str
dtypes: int64(1), str(5)
memory usage: 145.6 KB

In [11]:
providers.nunique()

Provider_ID    1000
Name            973
Type              4
Address        1000
City            963
Contact        1000
dtype: int64

In [12]:
# ==========================================
# RECEIVERS DATASET PROFILING
# ==========================================

In [13]:
receivers.shape

(1000, 5)

In [14]:
receivers.head()

   Receiver_ID          Name        Type               City           Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     (955)922-5295
1            2  Laurie Ramos  Individual         Lewisburgh      761.042.1570
2            3  Ashley Mckee         NGO  South Randalltown  691-023-0094x856
3            4    Erika Rose         NGO   South Shaneville        8296491111
4            5   John Romero  Individual          Bakerport      067.491.0154

In [15]:
receivers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   City         1000 non-null   str
 4   Contact      1000 non-null   str
dtypes: int64(1), str(4)
memory usage: 86.1 KB

In [16]:
receivers.isnull().sum()

Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

In [17]:
receivers.duplicated().sum()

np.int64(0)

In [18]:
receivers["Receiver_ID"].duplicated().sum()

np.int64(0)

In [19]:
receivers.nunique()

Receiver_ID    1000
Name            992
Type              4
City            966
Contact        1000
dtype: int64

In [20]:
receivers["Type"].value_counts()

Type
NGO           274
Charity       263
Shelter       246
Individual    217
Name: count, dtype: int64

In [21]:
# ==========================================
# FOOD LISTING DATASET PROFILING
# ==========================================

In [22]:
food_listings.shape

(1000, 9)

In [23]:
food_listings.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner

In [24]:
food_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   str
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   str
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   str
 6   Location       1000 non-null   str
 7   Food_Type      1000 non-null   str
 8   Meal_Type      1000 non-null   str
dtypes: int64(3), str(6)
memory usage: 124.2 KB

In [25]:
food_listings.isnull().sum()

Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

In [26]:
food_listings.duplicated().sum()

np.int64(0)

In [27]:
food_listings["Food_ID"].duplicated().sum()

np.int64(0)

In [28]:
food_listings.nunique()

Food_ID          1000
Food_Name          10
Quantity           50
Expiry_Date        15
Provider_ID       637
Provider_Type       4
Location          624
Food_Type           3
Meal_Type           4
dtype: int64

In [29]:
food_listings["Food_Type"].value_counts()

Food_Type
Vegetarian        336
Vegan             334
Non-Vegetarian    330
Name: count, dtype: int64

In [30]:
food_listings["Meal_Type"].value_counts()

Meal_Type
Breakfast    254
Snacks       253
Lunch        248
Dinner       245
Name: count, dtype: int64

In [31]:
food_listings["Provider_Type"].value_counts()

Provider_Type
Supermarket         267
Restaurant          258
Grocery Store       243
Catering Service    232
Name: count, dtype: int64

In [32]:
food_listings["Expiry_Date"].head()

0    3/17/2025
1    3/24/2025
2    3/28/2025
3    3/16/2025
4    3/19/2025
Name: Expiry_Date, dtype: str

In [33]:
# ==========================================
# CLAIMS DATASET PROFILING
# ==========================================

In [34]:
claims.shape

(1000, 5)

In [35]:
claims.head()

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

In [36]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   str
 4   Timestamp    1000 non-null   str
dtypes: int64(3), str(2)
memory usage: 61.2 KB

In [37]:
claims.isnull().sum()

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [38]:
claims.duplicated().sum()

np.int64(0)

In [39]:
claims["Claim_ID"].duplicated().sum()

np.int64(0)

In [40]:
claims.nunique()

Claim_ID       1000
Food_ID         647
Receiver_ID     624
Status            3
Timestamp       976
dtype: int64

In [41]:
claims["Status"].value_counts()

Status
Completed    339
Cancelled    336
Pending      325
Name: count, dtype: int64

In [42]:
claims["Timestamp"].head()

0      3/5/2025 5:26
1    3/11/2025 10:24
2     3/21/2025 0:59
3      3/4/2025 9:08
4    3/14/2025 15:17
Name: Timestamp, dtype: str

In [43]:
# ============================================
# DATABASE CONNECTION
# ============================================

from dotenv import load_dotenv
import os
from sqlalchemy import create_engine, text

# Load .env
load_dotenv()

# Read credentials
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

# Connection string
connection_string = (
    f"postgresql+psycopg2://"
    f"{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# Engine
engine = create_engine(connection_string)

# Test
with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("Connection successful:", result.fetchone())

Connection successful: (1,)

In [44]:
import sys
print(sys.executable)

c:\Users\rajuk\OneDrive\Desktop\Own Project\Local Food Wastage Management System\venv\Scripts\python.exe

In [45]:
import psycopg2
print("psycopg2 imported successfully")

psycopg2 imported successfully

In [46]:
# ============================================
# LOAD DATA INTO POSTGRESQL
# ============================================

providers.to_sql(
    "providers",
    engine,
    if_exists="replace",
    index=False
)

receivers.to_sql(
    "receivers",
    engine,
    if_exists="replace",
    index=False
)

food_listings.to_sql(
    "food_listings",
    engine,
    if_exists="replace",
    index=False
)

claims.to_sql(
    "claims",
    engine,
    if_exists="replace",
    index=False
)

print("All tables loaded successfully!")

All tables loaded successfully!

In [47]:
from sqlalchemy import text

with engine.connect() as conn:

    tables = conn.execute(
        text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
        """)
    )

    print("Tables in PostgreSQL:\n")

    for table in tables:
        print(table[0])

Tables in PostgreSQL:

claims
food_listings
providers
receivers

In [48]:
with engine.connect() as conn:

    for table in [
        "providers",
        "receivers",
        "food_listings",
        "claims"
    ]:

        result = conn.execute(
            text(f"SELECT COUNT(*) FROM {table}")
        )

        print(f"{table}: {result.scalar()}")

providers: 1000
receivers: 1000
food_listings: 1000
claims: 1000

In [49]:
# ============================================
# DATA TYPE CONVERSIONS
# ============================================

# Food Listings — convert Expiry_Date to datetime
food_listings["Expiry_Date"] = pd.to_datetime(
    food_listings["Expiry_Date"],
    format="%m/%d/%Y"
)

# Claims — convert Timestamp to datetime
claims["Timestamp"] = pd.to_datetime(
    claims["Timestamp"],
    format="%m/%d/%Y %H:%M"
)

# Verify conversions
print("food_listings dtypes after conversion:")
print(food_listings[["Food_ID", "Expiry_Date"]].dtypes)
print()
print("claims dtypes after conversion:")
print(claims[["Claim_ID", "Timestamp"]].dtypes)

food_listings dtypes after conversion:
Food_ID                 int64
Expiry_Date    datetime64[us]
dtype: object

claims dtypes after conversion:
Claim_ID              int64
Timestamp    datetime64[us]
dtype: object

In [50]:
# ============================================
# LOAD CLEANED DATA INTO POSTGRESQL
# ============================================

# Define table load order (parent tables first, child tables after)
tables = {
    "providers": providers,
    "receivers": receivers,
    "food_listings": food_listings,
    "claims": claims
}

for table_name, df in tables.items():
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False
    )
    print(f"Loaded: {table_name} — {len(df)} rows")

print("\nAll tables loaded successfully.")

Loaded: providers — 1000 rows
Loaded: receivers — 1000 rows
Loaded: food_listings — 1000 rows
Loaded: claims — 1000 rows

All tables loaded successfully.

In [52]:
# ============================================
# FEATURE ENGINEERING — ANALYSIS DATASET
# ============================================

# Merge claims with food_listings to get Expiry_Date alongside each claim
claims_analysis = claims.merge(
    food_listings[["Food_ID", "Expiry_Date", "Food_Type", "Meal_Type"]],
    on="Food_ID",
    how="left"
)

# Calculate Days_Until_Expiry (positive = claimed before expiry, negative = after)
claims_analysis["Days_Until_Expiry"] = (
    claims_analysis["Expiry_Date"] - claims_analysis["Timestamp"]
).dt.days

# Summary
print("claims_analysis shape:", claims_analysis.shape)
print()
print("Days_Until_Expiry distribution:")
print(claims_analysis["Days_Until_Expiry"].describe().round(2))
print()
print("Claims BEFORE expiry:", (claims_analysis["Days_Until_Expiry"] > 0).sum())
print("Claims ON expiry day:", (claims_analysis["Days_Until_Expiry"] == 0).sum())
print("Claims AFTER expiry :", (claims_analysis["Days_Until_Expiry"] < 0).sum())

claims_analysis shape: (1000, 9)

Days_Until_Expiry distribution:
count    1000.00
mean       10.89
std         7.14
min        -6.00
25%         6.00
50%        11.00
75%        16.00
max        28.00
Name: Days_Until_Expiry, dtype: float64

Claims BEFORE expiry: 925
Claims ON expiry day: 20
Claims AFTER expiry : 55

# Data Cleaning Summary

## Datasets Loaded

| Dataset       | Rows | Columns | Nulls | Duplicate IDs |
| ------------- | ---- | ------- | ----- | ------------- |
| Providers     | 1000 | 6       | 0     | 0             |
| Receivers     | 1000 | 5       | 0     | 0             |
| Food Listings | 1000 | 9       | 0     | 0             |
| Claims        | 1000 | 5       | 0     | 0             |

## Transformations Applied

* `Expiry_Date` converted from string to datetime using `%m/%d/%Y`
* `Timestamp` converted from string to datetime using `%m/%d/%Y %H:%M`
* Data types validated prior to PostgreSQL loading
* No missing values or duplicate primary keys detected
* No additional cleaning was required due to high data quality

## Feature Engineering

* Created an analysis dataset by merging `claims` and `food_listings`
* Engineered `Days_Until_Expiry` to measure the gap between claim timestamp and food expiry date

## Key Findings

* City fields contain synthetic data (~96% unique values); city-level insights should be interpreted cautiously
* Duplicate provider and receiver names represent distinct entities with unique IDs and do not require cleaning
* `Food_Name`, `Food_Type`, and `Meal_Type` function as independent categorical dimensions rather than a hierarchical classification
* 92.5% of claims occurred before food expiry
* 5.5% (55 claims) occurred after expiry, including 15 completed claims
* Because the dataset is synthetically generated, post-expiry claims should be interpreted as a data characteristic rather than definitive operational behavior

## PostgreSQL Load

* All four cleaned datasets loaded successfully into PostgreSQL database `food_wastage_db`
* `Expiry_Date` stored as PostgreSQL timestamp
* `Timestamp` stored as PostgreSQL timestamp
* Identifier fields stored as PostgreSQL bigint
* Data loaded using SQLAlchemy and psycopg2